### ISSUE TITLE
Parameterized modules support is being removed from erlang otp 21

### ISSUE THREAD

**Issue by miby00** [nitrogen/nitrogen#106]
This causes upload element and probably a few others to stop working.

This can be fixed in a few ways:

Add -compile(tuple_calls) to all modules using the removed feature.

Or

Add tuple_calls to rebar.config, I added it to nitrogen_core and simple_bridge.
That seemed to fix it for me. Example below.

{erl_opts, [tuple_calls]}.

Or 

Remove the feature from the code completely.

I would like to give my thanks for a great project, 
I have tested nitrogen for a few months now, and I love it!

**Comment by choptastic** [comment]
Awesome! Glad to hear you're enjoying it!

Thr tuple module removal fix is done on my test system and apparently I
forgot to push that to the live system.

But thank you for pointkng it out. I'll get this fixed soon.

-Jesse

**Comment by miby00** [comment]
Looking forward to it :-)

**Comment by choptastic** [comment]
Thanks, This has been fixed here: https://github.com/nitrogen/nitrogen_core/commit/add9e8a4eb2d0434675b104e1d44a7db7ca36b45 and https://github.com/nitrogen/nitrogen_core/commit/b8cc456b3d1eed8b68a3e56105fb006045924362
