### ISSUE TITLE
rebar3 release of a generated project: infinite recursion / cyclic dependency?

### ISSUE THREAD

**Issue by Olivier-Boudeville** [nitrogen/nitrogen#112]
Hi,

Starting from a fresh Nitrogen clone (master branch) and issuing 'make rel_cowboy' is to generate a new application (in '../myapp' by default), i.e. a self-contained Nitrogen project.

I suppose that we can generate an OTP release out of it? When trying to run 'rebar3 release' from the root of myapp (hopefully it is not a problem specific to my environment), the compilation of verl seems to run into an infinite loop or alike, and seems to hog the full RAM of the computer:

 $ rebar3 release
===> Fetching rebar3_hex v6.8.0
===> Version cached at XXX/.cache/rebar3/hex/hexpm/packages/rebar3_hex-6.8.0.tar is up to date, reusing it
===> Fetching hex_core v0.5.0
===> Version cached at XXX/.cache/rebar3/hex/hexpm/packages/hex_core-0.5.0.tar is up to date, reusing it
===> Fetching verl v1.0.1
===> Version cached at XXX/.cache/rebar3/hex/hexpm/packages/verl-1.0.1.tar is up to date, reusing it
===> Compiling verl
eheap_alloc: Cannot allocate 2733560184 bytes of memory (of type "heap").

(i.e. ~ 2.7 GB!)

FWIW, it is process <0.8.0> executing erlang:apply/2 and owning the package_index ETS table.

A bit in the same spirit, if making a slim cowboy release this time, the compilation of verl succeeds, but afterwards, in the generated project:

 $ rebar3 release
===> Fetching rebar3_hex v6.8.0
===> Version cached at XXX/.cache/rebar3/hex/hexpm/packages/rebar3_hex-6.8.0.tar is up to date, reusing it
===> Fetching hex_core v0.5.0
===> Version cached at XXX/.cache/rebar3/hex/hexpm/packages/hex_core-0.5.0.tar is up to date, reusing it
===> Fetching verl v1.0.1
===> Version cached at XXX/.cache/rebar3/hex/hexpm/packages/verl-1.0.1.tar is up to date, reusing it
===> Compiling verl
===> Compiling hex_core
===> Compiling rebar3_hex
===> Verifying dependencies...
===> Dependency cycle(s) detected:
applications: cf cowboy cowlib erlware_commons nitrogen_core nprocreg qdate qdate_localtime ranch simple_bridge simple_cache sync depend on each other

Reading the corresponding rebar.config, the enabled dependencies are (note that the comma mentioned in https://github.com/nitrogen/nitrogen/issues/111 had to be removed first):
    {cowboy,        {git, "git://github.com/ninenines/cowboy",         {tag, "2.4.0"}}},
    {simple_bridge, {git, "git://github.com/nitrogen/simple_bridge",{branch, master}}},
    {qdate,         {git, "git://github.com/choptastic/qdate",      {branch, master}}},
    {nprocreg,      {git, "git://github.com/nitrogen/nprocreg",     {branch, master}}},
    {nitrogen_core, {git, "git://github.com/nitrogen/nitrogen_core",{branch, master}}},
    {sync,          {git, "git://github.com/rustyio/sync",          {branch, master}}},
    {simple_cache,  {git, "git://github.com/nitrogen/simple_cache", {branch, master}}}

Not a showstopper for me currently, but I suppose it is better to report it.

Thanks!

Best regards,

Olivier.

**Comment by choptastic** [comment]
Closing this as a lot of work has been done on the rebar3 branch of nitrogen since this was posted, and no more cyclic dependencies exist :)
