### ISSUE TITLE
I can't create a new project with nitrogen

### ISSUE THREAD

**Issue by joshzinny** [nitrogen/nitrogen#114]
I am running Erlang/OTP 22 [erts-10.5]
make rel_inets, yaws, etc. does not work.

**Comment by choptastic** [comment]
Hi @joshzinny , I'm sorry I never responded.

1) Did you ever get it going?

2) If not, are you interested in still trying?

3) And if yes to (2) and you still get the error, what error do you get?

**Comment by choptastic** [comment]
I'm going to close this for now. If you come back, feel free to reopen it :)
