### ISSUE TITLE
Crash Handler Crashes

### ISSUE THREAD

**Issue by dotsiadia** [nitrogen/nitrogen#119]
On accessing the server in the browser is get **Internal Server Error**

This is what is displayed in the console

`Crash Handler Crashed:
{throw,
    {handler_not_found_in_context,crash_handler,
        [{handler_context,config_handler,default_config_handler,undefined,[]},
         {handler_context,log_handler,default_log_handler,undefined,[]},
         {handler_context,process_registry_handler,nprocreg_registry_handler,
             undefined,[]}]},
    [{wf_handler,get_handler,1,[{file,"src/lib/wf_handler.erl"},{line,92}]},
     {wf_handler,call_readonly,3,[{file,"src/lib/wf_handler.erl"},{line,60}]},
     {wf_core,run_crashed_first_request,3,
         [{file,"src/wf_core.erl"},{line,237}]},
     {wf_core,run_crash,4,[{file,"src/wf_core.erl"},{line,44}]},
     {httpd_response,traverse_modules,2, 
         [{file,"httpd_response.erl"},{line,82}]},
     {httpd_response,generate_and_send_response,1,
         [{file,"httpd_response.erl"},{line,45}]},
     {httpd_request_handler,handle_response,1,
         [{file,"httpd_request_handler.erl"},{line,626}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,680}]}]}`

`Original Crash:
{exit,{noproc,{gen_server,call,[nitro_cache_expirer,{new,nitrogen}]}},
      [{gen_server,call,2,[{file,"gen_server.erl"},{line,238}]},
       {nitro_cache,init,1,[{file,"src/nitro_cache.erl"},{line,48}]},
       {default_cache_handler,add_cache,2,
                              [{file,"src/handlers/cache/default_cache_handler.erl"},
                               {line,42}]},
       {default_cache_handler,init,2,
                              [{file,"src/handlers/cache/default_cache_handler.erl"},
                               {line,23}]},
       {wf_handler,init,1,[{file,"src/lib/wf_handler.erl"},{line,16}]},
       {wf_core,'-call_init_on_handlers/0-lc$^0/1-0-',1,
                [{file,"src/wf_core.erl"},{line,211}]},
       {wf_core,call_init_on_handlers,0,[{file,"src/wf_core.erl"},{line,211}]},
       {wf_core,run_catched,0,[{file,"src/wf_core.erl"},{line,86}]}]}`

**Comment by choptastic** [comment]
Hit @dotsiadia, I'm so sorry. I completely missed responding to this.

Is there any context to this.  When did the crashing start? 

It looks like this just needs to make sure that `nitro_cache` is started.  `simple_cache` was renamed to `nitro_cache` to avoid a naming clash, and the newest version of `simple_cache` is just an alias for `nitro_cache`.  You could try pulling down the latest version of `simple_cache` and it should all work from there.

Sorry again for the slow response.  I'm a butthead.

**Comment by dotsiadia** [comment]
@choptastic **nitrogen_sup.erl** file had been overwritten by that from older version of nitrogen upon transferring the source code to a new development environment running Nitrogen 2.4.0 . This led to the replacement of the  the line `application:start(nitro_cache)` with `application:start(simple_cache)` and as a result **nitro_cache** wasn't started on running Nitrogen. 

To mitigate this issue we decided to include both `application:start(nitro_cache)` and `application:start(simple_cache)` lines in  **nitrogen_sup.erl** file such that regardless of the Nitrogen version, the application runs!

**Comment by choptastic** [comment]
Excellent. Thanks for the update.
