### ISSUE TITLE
can't download nitrogen from the given link

### ISSUE THREAD

**Issue by balaji-s** [nitrogen/nitrogen#121]
When the linux binaries were clicked to download from the website, it opens the window in new tab and the browser pops the message saying

Warning: Potential Security Risk Ahead

Firefox detected a potential security threat and did not continue to downloads.nitrogenproject.com.s3.amazonaws.com. If you visit this site, attackers could try to steal information like your passwords, emails, or credit card details.

What can you do about it?

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

the above message is from firefox
The same has been verified in Opera

**Comment by choptastic** [comment]
Thank you for the heads up.  This has been fixed.
