### ISSUE TITLE
A wf_pandoc:convert(…) call with diacritics into the text fails

### ISSUE THREAD

**Issue by JiffB** [nitrogen/nitrogen#122]
Hi Jesse,

I may not use `wf_pandoc:convert/2` the right way (?), but if I call it from inside the `inner_body() ->` Fn, it fails, saying it can't find the temporary file.
 
It took me "some" time to find why and finally, not erasing the temporary file was the solution, as I found it was written with `iso-8859-1` encoding instead of `UTF-8`.
 
My first fix was to modify my call, adding a conversion to unicode: 
```
, wf_pandoc:convert(
    unicode:characters_to_binary(
        "bla bla"
    )
    , [ {from, creole}, {to, html5} ]
)
```
 
But in order to avoid to be obliged to do so within each and every call to `wf_pandoc:convert/2`, there is much simpler, modify `lib/nitrogen_core/src/lib/wf_pandoc.erl` as of this diff: 
```
7a8,9
> % =============================================================================
> 
11c13,16
<     file:write_file(RandFile, Contents),
---
>     %%% To avoid to add: unicode:characters_to_binary("mardown string") in the page call to: wf_pandoc(…), do it here
>     Utf8Contents = unicode:characters_to_binary(Contents),
>     %%%file:write_file(RandFile, Contents),
>     file:write_file(RandFile, Utf8Contents),
```

Jean-Yves

**Comment by choptastic** [comment]
Thanks for your change, I've added it to the `rebar3` branch of `nitrogen_core`
