### ISSUE TITLE
Commented line with a module reference in a template is still active

### ISSUE THREAD

**Issue by JiffB** [nitrogen/nitrogen#123]
Hi,

That means that if I have this kind of _commented_ line into a template : 
```
<!--span [[[header:header_under()]]]></span-->
```
and the `header` module has been striked, I get this error : 
```
throw:{unable_to_load_module,[{original_module,header},
                              {actual_module,header},
                              {function,button_connect},
                              {arg_string,[]}]}
--------------------------
```
(`button_connect` is another example of this bug in the same template)

It is abnormal that Nitrogen interprets a commented line the same way as regular's.

Jean-Yves

**Comment by choptastic** [comment]
Hi @JiffB, I'm so sorry I never responded to this.

The template parser isn't doing any interpreting of the HTML template beyond looking for `[[[` and `]]]`.  It would take additional work to have Nitrogen's HTML parser start actually parsing the HTML to ignore content in the HTML comments.

As of right now, this is not slated to be changed.
