### ISSUE TITLE
[Question] - Get keycode from keyup event

### ISSUE THREAD

**Issue by mobilemindtec** [nitrogen/nitrogen#126]
Hi,

How I can get key code from keyup event ?

```
wf:defer(search_text, #event { type=keyup, postback=on_search_keyup}),
```
```
event(Event) ->
    % get keycode??
    ok.
```

Thanks!

**Comment by choptastic** [comment]
This is a good question.  That specific postback mechanism unfortunately won't work.

The way you achieve this would be the use the `#api` actions with a little javascript:

```erlang
wf:wire(#api{name=search_keyup}),
wf:defer("objs(search_text).bind('keyup', function(e) { page.search_keyup(e.keyCode) })").
```

```erlang
api_event(search_keyup, _, KeyCode) ->
   do_something(KeyCode).
```

**Comment by mobilemindtec** [comment]
It would be nice to have this in the documentation. Thanks for the answer!
