### ISSUE TITLE
[Question] - How deploy nitrogen app

### ISSUE THREAD

**Issue by mobilemindtec** [nitrogen/nitrogen#127]
Hi,

I'm looking for how to deploy a nitrogen application but I couldn't find it. I found only deploy to heroku, but I need to deploy to a docker swarm on AWS. Would it just load the application with `bin/nitrogen start`?

Thanks!

**Comment by choptastic** [comment]
Hi @mobilemindtec, my apologies for the slow response.

I'm not able to guide you in how to deploy as a docker swarm - I don't use docker myself.  But the user @bunnylushington has a docker deployment example for apps they run: https://groups.google.com/g/nitrogenweb/c/oSVK9dadyVA/m/2svs0HKfAgAJ

The most basic means of deployment can simply be tarring it up, dropping on a server, untarring it and starting it:

```
$ tar cvzf myapp.tar.gz myapp
$ scp myapp.tar.gz user@myserver.com:~/
$ ssh user@myserver.com
(Logged in message)
$ tar xvzf myapp.tar.gz
$ cd myapp
*(options below)
$ bin/nitrogen console
```

`*` If you're running a full release, no need to do anything, but if you're running a slim release and the version of erlang on your dev machine differs from the version on your server, you'll want to run `make fix-slim-release && make`

With Nitrogen 3.x (not released yet), you can use more traditional rebar3 deployment methodologies.

**Comment by mobilemindtec** [comment]
Hello, thanks for the answer. Using in docker `CMD ["/app/bin/nitrogen", "foreground"]`. That worked fine.
