### ISSUE TITLE
nitrogen can't open ı don't know why last day not problem but today is not

### ISSUE THREAD

**Issue by ArchKubi** [nitrogen/nitrogen#128]
archkubi@GnuChanOS ~> nitrogen

(nitrogen:72710): Gtk-WARNING **: 08:21:00.047: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.047: Unable to locate theme engine in module_path: "clearlooks",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.047: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.047: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.047: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "clearlooks",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.048: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.049: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.049: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.049: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.049: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.049: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.049: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.049: Unable to locate theme engine in module_path: "murrine",

(nitrogen:72710): Gtk-WARNING **: 08:21:00.093: Could not find the icon 'image-x-generic'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases
Could not open dir /home/archkubi/.cache/yay/plymouth/pkg: Error opening directory “/home/archkubi/.cache/yay/plymouth/pkg”: Permission denied
Could not open dir /home/archkubi/.cache/yay/wxgtk-3.1.5/pkg: Error opening directory “/home/archkubi/.cache/yay/wxgtk-3.1.5/pkg”: Permission denied
Could not open dir /home/archkubi/.cache/yay/audacium/pkg: Error opening directory “/home/archkubi/.cache/yay/audacium/pkg”: Permission denied
Could not open dir /home/archkubi/.wine/dosdevices/z:/lost+found: Error opening directory “/home/archkubi/.wine/dosdevices/z:/lost+found”: Permission denied
Could not open dir /home/archkubi/.wine/dosdevices/z:/root: Error opening directory “/home/archkubi/.wine/dosdevices/z:/root”: Permission denied
Could not open dir /home/archkubi/.wine/dosdevices/z:/etc/sudoers.d: Error opening directory “/home/archkubi/.wine/dosdevices/z:/etc/sudoers.d”: Permission denied
Could not open dir /home/archkubi/.wine/dosdevices/z:/run/udisks2: Error opening directory “/home/archkubi/.wine/dosdevices/z:/run/udisks2”: Permission denied
Could not open dir /home/archkubi/.wine/dosdevices/z:/run/sudo: Error opening directory “/home/archkubi/.wine/dosdevices/z:/run/sudo”: Permission denied
Could not open dir /home/archkubi/.wine/dosdevices/z:/run/lightdm: Error opening directory “/home/archkubi/.wine/dosdevices/z:/run/lightdm”: Permission denied
Could not open dir /home/archkubi/.wine/dosdevices/z:/proc/65703: Error opening directory “/home/archkubi/.wine/dosdevices/z:/proc/65703”: No such file or directory
Could not open dir /home/archkubi/.wine/dosdevices/z:/boot/lost+found: Error opening directory “/home/archkubi/.wine/dosdevices/z:/boot/lost+found”: Permission denied
Could not open dir /home/archkubi/.wine/dosdevices/z:/srv/deluge: Error opening directory “/home/archkubi/.wine/dosdevices/z:/srv/deluge”: Permission denied
Could not open dir /home/archkubi/.wine/dosdevices/z:/tmp/systemd-private-0e3d6c7760d54f2281077208630b0269-upower.service-uVX3ja: Error opening directory “/home/archkubi/.wine/dosdevices/z:/tmp/systemd-private-0e3d6c7760d54f2281077208630b0269-upower.service-uVX3ja”: Permission denied
Could not open dir /home/archkubi/.wine/dosdevices/z:/tmp/systemd-private-0e3d6c7760d54f2281077208630b0269-systemd-logind.service-gsmeTY: Error opening directory “/home/archkubi/.wine/dosdevices/z:/tmp/systemd-private-0e3d6c7760d54f2281077208630b0269-systemd-logind.service-gsmeTY”: Permission denied
Could not open dir /home/archkubi/.wine/dosdevices/z:/tmp/systemd-private-0e3d6c7760d54f2281077208630b0269-systemd-timesyncd.service-ySnVqD: Error opening directory “/home/archkubi/.wine/dosdevices/z:/tmp/systemd-private-0e3d6c7760d54f2281077208630b0269-systemd-timesyncd.service-ySnVqD”: Permission denied

**Comment by choptastic** [comment]
Sorry for the delayed response. I think you might have found the wrong "Nitrogen" project on github.  This is for the [Nitrogen Web Framework for Erlang](https://nitrogenproject.com).
