### ISSUE TITLE
Creating a new app should include erlang_ls.config 

### ISSUE THREAD

**Issue by tatut** [nitrogen/nitrogen#130]
I'm new to Nitrogen and the default app `myapp` generated by the template compiles and starts, but erlang_ls has trouble with it by default.

<img width="938" alt="image" src="https://user-images.githubusercontent.com/83725/204101461-57b4ed16-04bb-458f-9f7f-851228816ddf.png">

For example it can't find wf.hrl or records.hrl. I think it would be good if the empty project template included a erlang_ls.config file which makes everything work.

**Comment by choptastic** [comment]
Hi @tatut,

This is actually something I've started working on - I just recently added erlang_ls to my own projects to get it working, and will be adding it to the default Nitrogen installation as well.

**Comment by tatut** [comment]
fwiw, I got it running with the following minimal config:

```yaml
deps_dirs:
  - "lib/*"
include_dirs:
  - "lib"
  - "lib/*/include"
```

but idk if there should be a plt built that includes the libs.

**Comment by choptastic** [comment]
This has been done in the rebar3 branch with this commit: https://github.com/nitrogen/nitrogen/commit/d605ebba63955f88e66c2a1e9e84678cfac86a8c
