### ISSUE TITLE
Trouble building Nitrogen

### ISSUE THREAD

**Issue by stanholzendorf** [nitrogen/nitrogen#131]
Hello,

I'm wanted to try out this framework and good the book as well "Build it with Nitrogen" but I'm having trouble of compiling it.
Running make `rel_inets PROJECT=myproj` fails for me.
Error message:

```
ERROR: Unable to generate spec: read file info /usr/lib64/erlang/lib/compiler-8.2.1/doc/chunks failed
ERROR: Unexpected error: rebar_abort
```

followed by

```
make[3]: *** [Makefile:317: generate] Error 1
make[2]: *** [Makefile:337: rel_inner_full] Error 
make[1]: *** [Makefile:226: rel] Error 2
make: *** [Makefile:116: rel_inets] Error 2
```

I'm on Fedora 37 and have Erlang installed through the repos.
Erlang Version is 25.1.2.
Inets is installed as well.
I also have rebar3 installed, should that matter.

EDIT:
I have removed rebar3, since nitrogen comes with rebar already.
Tried it again but the same issue unfortunately.

Thank you very much for your help.

**Comment by stanholzendorf** [comment]
OK. I was able to fix it actually. It was a simple folder issue. There was a symlink that was pointing to a non exiting folder for these chunks, which docgen was calling in the make file.
I simply added the chunks folders where they needed to be.

It build without incident after that.
This can be marked and/or move to solved.
Thank you.

**Comment by choptastic** [comment]
Hi @stanholzendorf!

When this happens, it has to do with some dangling symlinks floating about.  I don't know why they end up there, but you can safely delete the `/usr/lib64/erlang/lib/compiler-8.2.1/doc/chunks` file

So you should be able to do:

```bash
sudo rm /usr/lib64/erlang/lib/compiler-8.2.1/doc/chunks
```

And then try running the `make` command again.

I suspect there will be a handful of these dangling symlinks.  You can delete them one-by-one as they come up, or use a bash script to clean them up in bulk.

Give that a shot and let me know what happens.

**Comment by choptastic** [comment]
Oh hey, I just saw your response! Great you solved it.  You did it the non-destructive way! :)

Glad to hear it!  I'll close this particular issue.  Any more questions, feel free to ask!

**Comment by stanholzendorf** [comment]
Hi @choptastic 
That was it. Thank you so much. It compiled all the way after that.
Perfect.
