### ISSUE TITLE
Google charts API  (for QR codes) not available

### ISSUE THREAD

**Issue by SserwangaV** [nitrogen/nitrogen#146]
It seems Google Charts API is no longer available

`https://chart.apis.google.com/chart?cht=qr&chs=200x200&choe=UTF-8&chld=H&chl=` returns **404 Not Found**. Can we a work around?

**Comment by SserwangaV** [comment]
The API  appears to be deprecated. [See](https://developers.google.com/chart/infographics/docs/qr_codes)

**Comment by choptastic** [comment]
Oh no! I didn't realize that was going away!

Thanks!

Appreciate thr heads up.

I'm currently without my normal dev machine so any dev had been slowed to a
crawl while I get a secondary machine in place.

**Comment by SserwangaV** [comment]
@choptastic any progress on this issue.

**Comment by choptastic** [comment]
Sorry, not yet, but I'll try to take some time this week to fix them.

**Comment by SserwangaV** [comment]
@choptastic just a kind reminder on this issue.

**Comment by choptastic** [comment]
Hey @SserwangaV, sorry it took so long, but a fix has been pushed to all the relevant branches.

It requires a new dependency: https://github.com/nitrogen/nitro_qrcode

For Nitrogen 2.4: pull the new nitrogen from the `2.x` branch
For Nitrogen 3.0: You can either directly pull from the 3.0 branch (or the master branch, if you're in that transitionary state between 2.4 and 3.0).

**Comment by SserwangaV** [comment]
@choptastic Thank you.
