### ISSUE TITLE
Fail compilation on Erlang 18.0

### ISSUE THREAD

**Issue by fooflare** [nitrogen/nitrogen#89]
Hi, due to fail_on_warning option in:

https://github.com/nitrogen/nitrogen/blob/master/rel/overlay/rebar.config.src#L11

I get this warning and compilation fail:

simple_bridge/src/sb_file_upload_handler.erl:194: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
ERROR: compile failed while processing /home/fooflare/workspace/Nitrogen/nitrogen/rel/nitrogen/lib/simple_bridge: rebar_abort

Thanks.

**Comment by choptastic** [comment]
Thanks for the reminder!

If you pull the latest version of simple_bridge, it should compile properly
now.

-Jesse

On Wed, Jul 8, 2015 at 1:21 PM, Amos Oviedo <notifications@github.com>
wrote:

> Hi, due to fail_on_warning option in:
>
>
> https://github.com/nitrogen/nitrogen/blob/master/rel/overlay/rebar.config.src#L11
>
> I get this warning and compilation fail:
>
> simple_bridge/src/sb_file_upload_handler.erl:194: erlang:now/0: Deprecated
> BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS
> User's Guide for more information.
> ERROR: compile failed while processing
> /home/fooflare/workspace/Nitrogen/nitrogen/rel/nitrogen/lib/simple_bridge:
> rebar_abort
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nitrogen/nitrogen/issues/89>.
>



-- 
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by fooflare** [comment]
Hi again :) now it compiles fine. Because of the now() function there are 3 more warnings:

https://github.com/nitrogen/nprocreg/blob/master/src/nprocreg.erl#L154
https://github.com/nitrogen/nprocreg/blob/master/src/nprocreg.erl#L162
https://github.com/nitrogen/nitrogen_core/blob/master/src/lib/wf_render_elements.erl#L132

With these 3 warnings the compilation doesn't fail, but I tell you if you want to make something with them.

**Comment by choptastic** [comment]
I definitely know of those errors and I'm in the middle of refactoring all
of them out. For now the warnings are fine, and don't break anything.
Thanks for the reports!

On Wed, Jul 8, 2015 at 1:50 PM, Amos Oviedo <notifications@github.com>
wrote:

> Hi again :) now it compiles fine. Because of the now() function there are
> 3 more warnings:
>
> https://github.com/nitrogen/nprocreg/blob/master/src/nprocreg.erl#L154
> https://github.com/nitrogen/nprocreg/blob/master/src/nprocreg.erl#L162
>
> https://github.com/nitrogen/nitrogen_core/blob/master/src/lib/wf_render_elements.erl#L132
>
> With these 3 warnings the compilation doesn't fail, but I tell you if you
> want to make something with them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nitrogen/nitrogen/issues/89#issuecomment-119694982>.
>



-- 
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by choptastic** [comment]
I'm going to close this issue only because it will for sure be fixed for the next release of both Nitrogen, SimpleBridge, and nprocreg.
