### ISSUE TITLE
File uploading fails

### ISSUE THREAD

**Issue by slav1962** [nitrogen/nitrogen#93]
Using demo "File uploading" I try upload file which name contains cyrillic characters. The action fails. 

![fileupl](https://cloud.githubusercontent.com/assets/9305863/9954416/8d4a72d4-5df1-11e5-8291-31b3f0096e68.png)

Error message is in the attachment.

**Comment by choptastic** [comment]
Thanks for reporting this.

--
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by choptastic** [comment]
Fixed with latest simple_bridge master.  Thanks again for reporting!
